version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependecies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Unit Testing
          command: yarn test
      - store_test_results:
          path: test-results
